/home/baj321/.conda/envs/medfuse/lib/python3.6/site-packages/torch/cuda/__init__.py:143: UserWarning:
NVIDIA A100 80GB PCIe with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A100 80GB PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
==> training
Running unimodal pretraining for modality EHR
0
Starting val epoch 0
Traceback (most recent call last):
  File "fusion_main.py", line 128, in <module>
    trainer.train()
  File "/scratch/baj321/MedFuse/trainers/unimodal_trainer.py", line 238, in train
    ret = self.validate(self.val_dl)
  File "/scratch/baj321/MedFuse/trainers/unimodal_trainer.py", line 200, in validate
    v, cls = self.encoder(mod)
  File "/home/baj321/.conda/envs/medfuse/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/baj321/MedFuse/models/ehr_encoder.py", line 98, in forward
    ehr = self.to_ehr_embedding(ehr)  # Embed raw EHR data
  File "/home/baj321/.conda/envs/medfuse/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/baj321/.conda/envs/medfuse/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/baj321/.conda/envs/medfuse/lib/python3.6/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.